name: Release

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    env:
      TURBO_TELEMETRY_DISABLED: 1
      TURBO_TEAM: ${{ vars.TURBO_TEAM_MH }}
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: yarn install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            vercel pull --yes --environment=production --project=innocap-web --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --project=innocap-web --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Build Project
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            vercel build --prod --project=innocap-web --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --project=innocap-web --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Deploy to Vercel
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            vercel deploy --prebuilt --prod --project=innocap-web --token=${{ secrets.VERCEL_TOKEN }}
          else
            DEPLOY_URL=$(vercel deploy --prebuilt --project=innocap-web --token=${{ secrets.VERCEL_TOKEN }})
            echo "Deployed to: $DEPLOY_URL"
            vercel alias set $DEPLOY_URL ${{ vars.STAGING_DOMAIN }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ vars.TURBO_TEAM_MH }}
          fi
