name: Release

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    env:
      TURBO_TELEMETRY_DISABLED: 1
      TURBO_TEAM: ${{ secrets.TURBO_TEAM_MH }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: yarn install

      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest

      - name: Verify Vercel CLI Installation
        run: vercel --version

      - name: Pull Vercel Environment
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            vercel pull --yes --environment=production --token $VERCEL_TOKEN
          else
            vercel pull --yes --environment=preview --token $VERCEL_TOKEN
          fi

      - name: Deploy to Vercel
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            if ! vercel deploy --prod --token $VERCEL_TOKEN 2>&1 | tee deployment-url.txt; then
              echo "Production deployment failed! Error log:"
              cat deployment-url.txt
              exit 1
            fi
            DEPLOY_URL=$(tail -1 deployment-url.txt)
            echo "Production deployment URL: $DEPLOY_URL"
          else
            if ! vercel deploy --token $VERCEL_TOKEN 2>&1 | tee deployment-url.txt; then
              echo "Staging deployment failed! Error log:"
              cat deployment-url.txt
              exit 1
            fi
            DEPLOY_URL=$(tail -1 deployment-url.txt)
            echo "Staging deployment URL: $DEPLOY_URL"
            vercel alias set "$DEPLOY_URL" ${{ vars.STAGING_DOMAIN }} --token $VERCEL_TOKEN --scope ${{ vars.TURBO_TEAM_MH }}
          fi
