name: Release

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    env:
      TURBO_TELEMETRY_DISABLED: 1
      TURBO_TEAM: ${{ secrets.TURBO_TEAM_MH }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: yarn install

      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest

      - name: Verify Vercel CLI Installation
        run: vercel --version

      - name: Pull Vercel Environment
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            vercel pull --yes --environment=production --token $VERCEL_TOKEN
          else
            vercel pull --yes --environment=preview --token $VERCEL_TOKEN
          fi

      - name: Build with Vercel
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            vercel build --prod --token $VERCEL_TOKEN
          else
            vercel build --token $VERCEL_TOKEN
          fi

      - name: Deploy to Vercel
        run: |
          deploy_prebuilt() {
            vercel deploy --prebuilt $@ 2>&1 | tee deployment-url.txt
            if [ ${PIPESTATUS[0]} -eq 0 ]; then
              DEPLOY_URL=$(tail -1 deployment-url.txt)
              echo "Deployment URL: $DEPLOY_URL"
              return 0
            else
              echo "Deployment failed! Error log:"
              cat deployment-url.txt
              return 1
            fi
          }

          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            if ! deploy_prebuilt --prod --token $VERCEL_TOKEN; then
              exit 1
            fi
          else
            if deploy_prebuilt --token $VERCEL_TOKEN; then
              DEPLOY_URL=$(tail -1 deployment-url.txt)
              vercel alias set $DEPLOY_URL ${{ vars.STAGING_DOMAIN }} --token $VERCEL_TOKEN --scope ${{ vars.TURBO_TEAM_MH }}
            else
              exit 1
            fi
          fi
